site_name: RuneAudio
site_url: http://www.runeaudio.com/documentation/
site_description: 'RuneAudio documentation - Free and open source Hi-Fi music player for embedded hardware.'
site_author: 'Andrea Coiutti (ACX)'
site_favicon: favicon.ico
repo_url: https://github.com/RuneAudio/Docs/
theme_dir: 'runeaudio_theme'
dev_addr: 127.0.0.1:8080

pages:
- ['index.md', 'Docs']
- ['quick-start\quick-start-guide.md', 'Quick start', 'Quick start guide']
- ['quick-start\sd-card-setup-windows.md', 'Quick start', 'Flashing the SD Card using Windows']
- ['quick-start\sd-card-setup-mac.md', 'Quick start', 'Flashing the SD Card using Mac']
- ['quick-start\sd-card-setup-linux.md', 'Quick start', 'Flashing the SD Card using Linux']
- ['quick-start\rpi-hardware-setup.md', 'Quick start', 'Raspberry Pi hardware setup']
- ['runeui\runeui.md', 'RuneUI', 'RuneUI']
- ['runeui\playback.md', 'RuneUI', 'Playback']
- ['runeui\sources.md', 'RuneUI', 'Sources']
- ['runeui\mpd.md', 'RuneUI', 'MPD']
- ['runeui\settings.md', 'RuneUI', 'Settings']
- ['runeui\network.md', 'RuneUI', 'Network']
- ['runeui\debug.md', 'RuneUI', 'Debug']
- ['troubleshooting\common-troubleshooting.md', 'Troubleshoot', 'Common troubleshooting']
- ['troubleshooting\rpi-troubleshooting.md', 'Troubleshoot', 'Raspberry Pi troubleshooting']
- ['troubleshooting\updating.md', 'Troubleshoot', 'Getting updates']
- ['development\contribute.md', 'Dev', 'Contribute']